In [10]:
import sys
from pathlib import Path

sys.path.append(str(Path("../pipeline").resolve()))

from prepare_bcg_data import run_pipeline

In [12]:
updated_bcg_info = run_pipeline()
updated_bcg_info

INFO: Found 29 FITS files.
INFO: Processing 1/29: member.0099-00913_revised.fits
INFO: Processing 2/29: member.COMBO-17_48654_revised.fits
INFO: Processing 3/29: member.D32064369_sci.spw23.cube.I.pbcor.fits
INFO: Processing 4/29: member.OzDES-DR2_04572_revised.fits
INFO: Processing 5/29: member.OzDES-DR2_04586_revised.fits
INFO: Processing 6/29: member.SVA1_COADD-2938085330_revised.fits
INFO: Processing 7/29: member.SVA1_COADD-2938301050_revised.fits
INFO: Processing 8/29: member.SVA1_COADD-2938633040_revised.fits
INFO: Processing 9/29: member.SVA1_COADD-2938639684_100kms.fits
INFO: Processing 10/29: member.SVA1_COADD-2938863443_revised.fits
INFO: Processing 11/29: member.SVA1_COADD-2938969684_revised.fits
INFO: Processing 12/29: member.SVA1_COADD-2939015646_revised.fits
INFO: Processing 13/29: member.SVA1_COADD-2939717201_revised.fits
INFO: Processing 14/29: member.SVA1_COADD-2939719204_50kms.fits
INFO: Processing 15/29: member.SVA1_COADD-2940246152_revised.fits
INFO: Processing 16/29: member.SVA1_COADD-2940452469_revised.fits
INFO: Processing 17/29: member.SVA1_COADD-2940683398_revised.fits
INFO: Processing 18/29: member.SVA1_COADD-2940843752_revised.fits
INFO: Processing 19/29: member.SVA1_COADD-2940897556_revised.fits
INFO: Processing 20/29: member.SVA1_COADD-2940961062_revised.fits
INFO: Processing 21/29: member.SVA1_COADD-2943192601_revised.fits
INFO: Processing 22/29: member.SVA1_COADD-2970368709_100kms.fits
INFO: Processing 23/29: member.SVA1_COADD-2970489493_revised.fits
INFO: Processing 24/29: member.SVA1_COADD-2970674189_revised.fits
INFO: Processing 25/29: member.SVA1_COADD-2970773686_revised.fits
INFO: Processing 26/29: member.SVA1_COADD-2971029799_75kms.fits
INFO: Processing 27/29: member.SVA1_COADD-2971195115_revised.fits
INFO: Processing 28/29: member.VIPERS_124019364_revised.fits
INFO: Processing 29/29: member._1237679323935343274_revised.fits
INFO: Saved 29 processed targets to ../BCG Data/Updated/Basic BCG Info - updated.csv

,ID,Original ID,RA (deg),DEC (deg),z,CO (2-1) (GHz),BMAJ (arcsec),BMIN (arcsec),BPA (deg),Match separation (arcsec),Original FITS file,Updated FITS file
0,SpARCS0035-4303,0099-00913,8.888883,-43.051319,0.838361,125.404123,2.612341,2.123972,79.323898,0.000456,member.0099-00913_revised.fits,SpARCS0035-4303.fits
1,SpARCS0332-2740,COMBO-17_48654,53.189610,-27.681410,0.740000,132.493103,3.711323,1.905093,-83.066269,0.048086,member.COMBO-17_48654_revised.fits,SpARCS0332-2740.fits
2,SpARCS0331-2732,D32064369,52.884041,-27.535271,0.763930,130.695661,2.032111,1.612080,-82.527611,0.000666,member.D32064369_sci.spw23.cube.I.pbcor.fits,SpARCS0331-2732.fits
3,SpARCS0026-4300,OzDES-DR2_04572,6.711721,-43.003090,0.547610,148.963888,2.337477,1.858479,84.064537,0.000439,member.OzDES-DR2_04572_revised.fits,SpARCS0026-4300.fits
4,SpARCS0036-4414,OzDES-DR2_04586,9.082426,-44.249378,0.838190,125.415761,2.638438,2.300144,77.217201,0.000474,member.OzDES-DR2_04586_revised.fits,SpARCS0036-4414.fits
5,SpARCS0221-0550,SVA1_COADD-2938085330,35.361526,-5.847661,0.745230,132.096055,2.812235,2.091939,72.345039,0.000719,member.SVA1_COADD-2938085330_revised.fits,SpARCS0221-0550.fits
6,SpARCS0220-0600,SVA1_COADD-2938301050,35.055283,-6.015242,0.654020,139.380418,2.444299,1.958387,83.677002,0.000359,member.SVA1_COADD-2938301050_revised.fits,SpARCS0220-0600.fits
7,SpARCS0219-0505,SVA1_COADD-2938633040,34.828926,-5.086895,0.518760,151.793566,3.059742,1.831284,-79.743813,0.000598,member.SVA1_COADD-2938633040_revised.fits,SpARCS0219-0505.fits
8,SpARCS0218-0500,SVA1_COADD-2938639684,34.521568,-5.002926,1.093360,110.128218,2.832822,1.521083,-73.668098,0.000499,member.SVA1_COADD-2938639684_100kms.fits,SpARCS0218-0500.fits
9,SpARCS0222-0421,SVA1_COADD-2938863443,35.554077,-4.366205,0.827430,126.154216,3.168015,2.250434,-83.325760,0.000299,member.SVA1_COADD-2938863443_revised.fits,SpARCS0222-0421.fits
10,SpARCS0225-0447,SVA1_COADD-2938969684,36.278847,-4.788445,0.832980,125.772241,2.924096,2.255986,80.096802,0.000299,member.SVA1_COADD-2938969684_revised.fits,SpARCS0225-0447.fits
11,SpARCS0225-0428,SVA1_COADD-2939015646,36.480087,-4.480370,1.011660,114.600878,2.332865,1.532758,-64.253014,0.000299,member.SVA1_COADD-2939015646_revised.fits,SpARCS0225-0428.fits
12,SpARCS0333-2932,SVA1_COADD-2939717201,53.484268,-29.539351,0.559710,147.808244,2.731541,1.830058,-87.177383,0.000478,member.SVA1_COADD-2939717201_revised.fits,SpARCS0333-2932.fits
13,SpARCS0334-2930,SVA1_COADD-2939719204,53.683449,-29.508631,1.094890,110.047783,2.192420,1.607862,86.964821,0.000658,member.SVA1_COADD-2939719204_50kms.fits,SpARCS0334-2930.fits
14,SpARCS0335-2918,SVA1_COADD-2940246152,53.865639,-29.304640,0.558470,147.925849,2.595424,1.829746,-89.399155,0.000523,member.SVA1_COADD-2940246152_revised.fits,SpARCS0335-2918.fits
15,SpARCS0330-2709,SVA1_COADD-2940452469,52.732750,-27.154209,0.793890,128.512897,2.641304,1.922335,85.245117,0.000400,member.SVA1_COADD-2940452469_revised.fits,SpARCS0330-2709.fits
16,SpARCS0333-2838,SVA1_COADD-2940683398,53.496651,-28.636250,0.664490,138.503687,2.511154,1.878952,80.521439,0.000527,member.SVA1_COADD-2940683398_revised.fits,SpARCS0333-2838.fits
17,SpARCS0326-2818,SVA1_COADD-2940843752,51.661991,-28.316290,0.541700,149.534928,3.086340,1.762833,-83.171936,0.000528,member.SVA1_COADD-2940843752_revised.fits,SpARCS0326-2818.fits
18,SpARCS0328-2753,SVA1_COADD-2940897556,52.138630,-27.892429,1.132990,108.082082,2.180530,1.518601,-86.445694,0.000400,member.SVA1_COADD-2940897556_revised.fits,SpARCS0328-2753.fits
19,SpARCS0329-2903,SVA1_COADD-2940961062,52.465809,-29.059429,0.725830,133.580942,2.537074,1.942719,81.260872,28.320846,member.SVA1_COADD-2940961062_revised.fits,SpARCS0329-2903.fits
20,SpARCS0036-4449,SVA1_COADD-2943192601,9.223277,-44.831612,0.805050,127.718345,2.763762,2.316791,74.960342,0.000292,member.SVA1_COADD-2943192601_revised.fits,SpARCS0036-4449.fits
21,SpARCS0027-4334,SVA1_COADD-2970368709,6.942504,-43.571140,0.536960,149.996096,2.385970,1.906116,84.684319,0.000435,member.SVA1_COADD-2970368709_100kms.fits,SpARCS0027-4334.fits
22,SpARCS0036-4238,SVA1_COADD-2970489493,9.074923,-42.647709,0.811760,127.245330,2.849042,2.282579,77.008896,0.000457,member.SVA1_COADD-2970489493_revised.fits,SpARCS0036-4238.fits
23,SpARCS0034-4413,SVA1_COADD-2970674189,8.565585,-44.220409,1.031370,113.488924,4.707527,2.302436,-88.293755,0.000400,member.SVA1_COADD-2970674189_revised.fits,SpARCS0034-4413.fits
24,SpARCS0036-4328,SVA1_COADD-2970773686,9.119555,-43.475460,0.397500,164.964579,1.985933,1.633520,-71.808838,0.000000,member.SVA1_COADD-2970773686_revised.fits,SpARCS0036-4328.fits
25,SpARCS0029-4257,SVA1_COADD-2971029799,7.387458,-42.954418,1.024470,113.875732,2.685004,2.289866,-88.845078,0.856800,member.SVA1_COADD-2971029799_75kms.fits,SpARCS0029-4257.fits
26,SpARCS0033-4304,SVA1_COADD-2971195115,8.259990,-43.079971,1.024310,113.884732,3.449419,2.337395,82.184738,0.000400,member.SVA1_COADD-2971195115_revised.fits,SpARCS0033-4304.fits
27,SpARCS0220-0436,VIPERS_124019364,35.117302,-4.604064,1.081100,110.776994,3.019011,2.447542,-86.077423,0.000499,member.VIPERS_124019364_revised.fits,SpARCS0220-0436.fits
28,SpARCS0222-0350,_1237679323935343274_,35.652096,-3.841740,0.535236,150.164581,2.457465,1.908564,78.226562,0.000599,member._1237679323935343274_revised.fits,SpARCS0222-0350.fits

In [14]:
updated_bcg_info[
    [
        "ID",
        "z",
        "BMAJ (arcsec)",
        "BMIN (arcsec)",
        "BPA (deg)"
    ]
]

                 ID         z  BMAJ (arcsec)  BMIN (arcsec)  BPA (deg)
0   SpARCS0035-4303  0.838361       2.612341       2.123972  79.323898
1   SpARCS0332-2740  0.740000       3.711323       1.905093 -83.066269
2   SpARCS0331-2732  0.763930       2.032111       1.612080 -82.527611
3   SpARCS0026-4300  0.547610       2.337477       1.858479  84.064537
4   SpARCS0036-4414  0.838190       2.638438       2.300144  77.217201
5   SpARCS0221-0550  0.745230       2.812235       2.091939  72.345039
6   SpARCS0220-0600  0.654020       2.444299       1.958387  83.677002
7   SpARCS0219-0505  0.518760       3.059742       1.831284 -79.743813
8   SpARCS0218-0500  1.093360       2.832822       1.521083 -73.668098
9   SpARCS0222-0421  0.827430       3.168015       2.250434 -83.325760
10  SpARCS0225-0447  0.832980       2.924096       2.255986  80.096802
11  SpARCS0225-0428  1.011660       2.332865       1.532758 -64.253014
12  SpARCS0333-2932  0.559710       2.731541       1.830058 -87.177383
13  SpARCS0334-2930  1.094890       2.192420       1.607862  86.964821
14  SpARCS0335-2918  0.558470       2.595424       1.829746 -89.399155
15  SpARCS0330-2709  0.793890       2.641304       1.922335  85.245117
16  SpARCS0333-2838  0.664490       2.511154       1.878952  80.521439
17  SpARCS0326-2818  0.541700       3.086340       1.762833 -83.171936
18  SpARCS0328-2753  1.132990       2.180530       1.518601 -86.445694
19  SpARCS0329-2903  0.725830       2.537074       1.942719  81.260872
20  SpARCS0036-4449  0.805050       2.763762       2.316791  74.960342
21  SpARCS0027-4334  0.536960       2.385970       1.906116  84.684319
22  SpARCS0036-4238  0.811760       2.849042       2.282579  77.008896
23  SpARCS0034-4413  1.031370       4.707527       2.302436 -88.293755
24  SpARCS0036-4328  0.397500       1.985933       1.633520 -71.808838
25  SpARCS0029-4257  1.024470       2.685004       2.289866 -88.845078
26  SpARCS0033-4304  1.024310       3.449419       2.337395  82.184738
27  SpARCS0220-0436  1.081100       3.019011       2.447542 -86.077423
28  SpARCS0222-0350  0.535236       2.457465       1.908564  78.226562